server:
  port: 8080

---

spring:
  profiles: default
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://user03.database.windows.net:1433;database=yanolja;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: rhdkfma77@user03
    password: srhkjrm7614!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Viewer
          destination: yanolja
          contentType: application/json
        event-out:
          destination: yanolja
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8084
---

spring:
  profiles: docker
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://user03.database.windows.net:1433;database=yanolja;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: rhdkfma77@user03
    password: ${configmap}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
      generate-ddl: true  
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Viewer
          destination: yanolja
          contentType: application/json
        event-out:
          destination: yanolja
          contentType: application/json